CREATE TABLE WT_PART (
    PART_ID INT IDENTITY(1,1) PRIMARY KEY,
    PART_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    PART_NAME VARCHAR(255) NOT NULL,
    REVISION VARCHAR(10) NOT NULL,
    LIFECYCLE_STATE VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
    MODIFIED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL
);